name: Mirror

on:
    push:
        branches: 
            - "**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: mirror-repository
            - uses: spyoungtech/mirror-action@master
            with:
                REMOTE: https://git.stboyden.com/rusty-matrix
                GIT_USERNAME: STBoyden
                GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
